template:
    params:
      title: "Kaleb McKone"
      projectName: "Kaleb's Notes"
      myName: "Kaleb McKone"
    styles:
      sheetURL: "https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css"
