environment:
  steamId: "76561197988460908"
template:
  params:
    title: "Kaleb McKone"
    projectName: "Portfolio"
    myName: "KRM"
    subtitle: "Always in Development"
  styles:
    sheetURL: "https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css"
  icons:
    github: "github.svg"
    linkedin: "linkedin.svg"
