template:
    params:
      title: "Kaleb McKone"
      projectName: "Software Engineer"
      myName: "Kaleb McKone"
      githubURL: "https://github.com/krmckone"
    styles:
      sheetURL: "https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css"
      fontURL: "https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300&display=swap"
      iconURL: "https://kit.fontawesome.com/a307c0310b.js"