template:
    params:
      title: "Kaleb's Site"
      projectName: "A Static Site Generator"
      myName: "Kaleb McKone"
    styles:
      sheetURL: "https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css"