environment:
  params:
    steamId: "76561197988460908"
template:
  params:
    title: "Kaleb McKone"
    projectName: "Portfolio"
    myName: "KRM"
    subtitle: "Always in Development"
  styles:
    sheetURL: "https://cdn.jsdelivr.net/gh/mikemai2awesome/mcss@main/mcss.css"
  icons:
    github: "github.svg"
    linkedin: "linkedin.svg"
