name: Build and Test

on:
  workflow_call:

jobs:
  build:
    outputs:
      artifact_id: ${{ steps.upload-static-artifacts.outputs.artifact-id }}
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ^1.22
    - run: go version

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Build Static
      run: go run cmd/lk-site/main.go

    - name: Check HTML
      uses: anishathalye/proof-html@v2
      with:
        directory: ./build
        check_favicon: false
    - name: Upload Static Artifacts
      id: upload-static-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: ./build
